version: '3'
services:

    # PHP Service
    backend:
        build:
            context: .
            dockerfile: ./docker/backend/DockerFile
        container_name: "backend"
        tty: true
        environment:
            SERVICE_NAME: backend
        working_dir: /var/www/backend
        volumes:
            - ./backend/rokko_gw/:/var/www/backend
            - ./docker/backend/supervisor/supervisord.conf:/etc/supervisord.conf
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        # command: >
        #     bash -c "composer update"
        networks:
            - private 

    # Frontend Service
    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend/DockerFile
        container_name: "frontend"
        working_dir: /usr/src/app/frontend
        volumes:
            - ./frontend/rokko_fe/:/usr/src/app/frontend
        ports:
            - '4200:4200'
        command: >
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
        networks:
            - private

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: "webserver"
        tty: true
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./backend/rokko_gw/:/var/www/backend
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - private

    # MySQL Service
    mysql:
        image: mariadb:10.6
        container_name: "mysql"
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/dbdata/:/var/lib/mysql-files/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - private

    # PHPMYADMIN Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "phpmyadmin"
        ports:
            - "7000:80"
        links:
            - mysql:mysql
        environment:
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
            PMA_HOST: mysql
        networks:
            - private

# Docker Networks
networks:
    private:
        driver: bridge
